Add state dump representation
andreykaere/bspc-rs pull request #2
Opened 2023-08-13 20:01 UTC by WhySoBad

# Add state dump representation

Added `State` struct which represents a state dump of bspwm. This is useful for use cases which want to keep track of the bspwm state internally since it's an easy way to get the whole state at once instead of fetching every monitor, desktop and window individually.

## Changes made
* Added `State` struct which represents a bspwm state dump
* Added `get_current_state` method for getting a `State` instance of the current bspwm state

2023-08-14 09:11 UTC, andreykaere commented
Hi! Can you, please, format your commits, according to this style: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

And apply rustfmt, please, to pass the checks. 

I will have a look at the content of your PR a bit later

2023-08-14 09:26 UTC, WhySoBad commented
Sorry, I didn't look at your previous commits which follow these guidelines. 
My personal preference is all lowercase but I'll change it later today.

2023-08-18 08:14 UTC, WhySoBad commented
I've updated the commit messages to follow your provided naming scheme. Sorry it took a bit longer than anticipated. I didn't find the time the last few days.

2023-08-19 19:50 UTC, andreykaere commented on src/state.rs
> +    let mut conn = connect()?;
I would stick to the style `socket::connect()?` here. Also, you don't need `format` macro here. So, I would like it to be changed to
```rust
let mut conn = socket::connect()?;

2023-08-19 19:53 UTC, andreykaere requested changes
Hey, kindly take a look at some changes I've requested

2023-08-19 19:53 UTC, andreykaere commented on src/state.rs
> +    let mut conn = connect()?;
```suggestion
    let mut conn = socket::connect()?;
```

2023-08-19 19:53 UTC, andreykaere commented on src/state.rs
> +    let request = format!("wm\x00-d\x00");
```suggestion

```

2023-08-19 19:53 UTC, andreykaere commented on src/state.rs
> +    conn.send_message(&request)?;
```suggestion
    conn.send_message("wm\x00-d\x00")?;
```

2023-08-19 19:54 UTC, andreykaere commented
And `cargo fmt --check` still fails ...

2023-08-19 19:56 UTC, andreykaere commented on src/state.rs
> +use crate::socket::{connect, BspcCommunication};
```suggestion
use crate::socket::{self, BspcCommunication};
```

2023-08-19 20:06 UTC, andreykaere commented
Also ... It seems that `State` struct is missing the field `pub primary_monitor_id: Id`.

2023-08-19 21:06 UTC, andreykaere commented
It seems that field `primary_monitor_id` is optional ...

2023-08-19 21:12 UTC, andreykaere commented
By the way, what is `state.len() > 1` for? I mean, what is logic behind it?

2023-08-19 21:20 UTC, WhySoBad commented
> It seems that field `primary_monitor_id` should be optional ...
> 
> UPD: I checked, `Option<Id>` will do it

This makes sense. I wondered why I haven't added this field in the past but I remember setting my primary explicitly only a few days ago. I'll change it.



> By the way, what is `state.len() > 1` for? I mean, what is logic behind it?

As already mentioned I don't really see the sense in those tests since they don't make any assertions or similar. 
This test is heavily inspired by the `parse_tree` test in the tree module:
https://github.com/andreykaere/bspc-rs/blob/b1fccfdc8ec8b69f642ebbd5993edf063ccc72d9/src/tree.rs#L169C1-L172C10+

2023-08-19 21:37 UTC, andreykaere commented
Well, in `parse_tree` I guess it was added for the sake of CI, because I guess it's impossible to test `parse_tree` there, since there is no monitor. And this condition just makes CI ignore this test, as I remember. Why there is `.len() > 1` and not `is_empty()` or something, I have no idea :)

Anyway, I guess I will merge it now and if something will come up in the future, I'll just change it.

2023-08-19 21:40 UTC, merged